name: docker-build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-debug-windows:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ runner.os }}-windows-godot-cpp
          restore-keys: |
            ${{ runner.os }}-windows-godot-
            ${{ runner.os }}-windows-

      - name: Docker build Windows x86_64
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose run windows_x86_64

      - name: Docker build Windows x86_32
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose run windows_x86_32

      - uses: actions/upload-artifact@v4
        with:
          name: windows-debug
          path: bin/windows

      - uses: actions/cache/save@v4
        id: cache
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ runner.os }}-windows-godot-cpp

  build-debug-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ runner.os }}-linux-godot-cpp
          restore-keys: |
            ${{ runner.os }}-linux-godot-
            ${{ runner.os }}-linux-

      - name: Docker build Linux x86_64
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose run linux_x86_64

      - name: Docker build Linux x86_32
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose run linux_x86_32

      - uses: actions/upload-artifact@v4
        with:
          name: linux-debug
          path: bin/linux

      - uses: actions/cache/save@v4
        id: cache
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ runner.os }}-linux-godot-cpp

  build-debug-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ runner.os }}-android-godot-cpp
          restore-keys: |
            ${{ runner.os }}-android-godot-
            ${{ runner.os }}-android-

      - name: Docker build Android x86_64
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose run android_x86_64

      - name: Docker build Android x86_32
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose run android_x86_32

      - name: Docker build Android arm64
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose run android_arm64

      - name: Docker build Android arm32
        run: sudo chmod 777 docker-storage/entrypoint.sh |
          docker compose run android_arm32

      - uses: actions/upload-artifact@v4
        with:
          name: android-debug
          path: bin/android

      - uses: actions/cache/save@v4
        id: cache
        with:
          path: |
            godot-cpp/
            .sconsign.dblite
          key: ${{ runner.os }}-android-godot-cpp